project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - general/*.qmd
    - part-01/*.qmd
    - part-02/*.qmd

website:
  title: "Applied Optimization with Julia"
  repo-url: https://github.com/beyondsimulations/Applied-Optimization
  repo-actions: [edit, source, issue]
  site-url: https://beyondsimulations.github.io/Applied-Optimization
  bread-crumbs: true
  sidebar:
    style: floating
    collapse-level: 1 
    search: true
    contents:
      - text: "Welcome"
        href: index.qmd
      - text: "Syllabus"
        href: general/syllabus.qmd
      - text: "01 Introduction "
        href: part-01/lecture-introduction.qmd
      - section: "02 First Steps"
        contents:
          - text: "Lecture"
            href: part-02/lecture-firststeps.qmd
          - text: "Tutorial 02-01"
            href: part-02/tutorial-02-01-variables.qmd
          - text: "Tutorial 02-02"
            href: part-02/tutorial-02-02-vectors.qmd
          - text: "Tutorial 02-03"
            href: part-02/tutorial-02-03-comparisons.qmd
          - text: "Tutorial 02-04"
            href: part-02/tutorial-02-04-loops.qmd
          - text: "Tutorial 02-05"
            href: part-02/tutorial-02-05-scope.qmd
      - text: "FAQs"
        href: general/faq.qmd
      - text: "Literature"
        href: general/literature.qmd
  page-footer: 
    center: "Applied Optimization with Julia, Tobias Vlćek</br>CC BY-NC-SA 4.0" 
    right: 
      - icon: github
        href: https://github.com/beyondsimulations/Applied-Optimization
      - icon: linkedin
        href: https://linkedin.com/in/tobiasvlcek

format:
  html:
    theme: litera
    css: styles.css
    toc: true
  pdf:
    include-in-header: 
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}


