project:
  type: website
  render:
    - 404.qmd
    - index.qmd
    - general/*.qmd
    - part-01/*.qmd
    - part-02/*.qmd
    - part-03/*.qmd
    - part-04/*.qmd
    - part-05/*.qmd
    - part-06/*.qmd
    - part-07/lecture-routing.qmd
    
website:
  title: "Applied Optimization with Julia"
  repo-url: https://github.com/beyondsimulations/Applied-Optimization
  repo-actions: [edit, source, issue]
  site-url: https://beyondsimulations.github.io/Applied-Optimization
  bread-crumbs: true
  sidebar:
    style: floating
    collapse-level: 1 
    search: true
    contents:
      - text: "Welcome"
        href: index.qmd
      - text: "Syllabus"
        href: general/syllabus.qmd
      - text: "***"
      - text: "01 Introduction"
        href: part-01/lecture-introduction.qmd
      - section: "02 First Steps"
        contents:
          - text: "Lecture"
            href: part-02/lecture-firststeps.qmd
          - text: "01 - Variables"
            href: part-02/tutorial-02-01-variables.qmd
          - text: "02 - Vectors"
            href: part-02/tutorial-02-02-vectors.qmd
          - text: "03 - Comparisons"
            href: part-02/tutorial-02-03-comparisons.qmd
          - text: "04 - Loops"
            href: part-02/tutorial-02-04-loops.qmd
          - text: "05 - Dictionaries"
            href: part-02/tutorial-02-05-dicts.qmd
      - section: "03 Data"
        contents:
          - text: "Lecture"
            href: part-03/lecture-packages.qmd
          - text: "01 - Functions"
            href: part-03/tutorial-03-01-functions.qmd
          - text: "02 - Packages"
            href: part-03/tutorial-03-02-handling.qmd
          - text: "03 - DataFrames"
            href: part-03/tutorial-03-03-DataFrames.qmd
          - text: "04 - Input and Output"
            href: part-03/tutorial-03-04-IO.qmd
          - text: "05 - Plotting"
            href: part-03/tutorial-03-05-Plotting.qmd
      - section: "04 Optimization"
        contents:
          - text: "Lecture"
            href: part-04/lecture-jump.qmd
          - text: "01 - JuMP"
            href: part-04/tutorial-04-01-jump.qmd
          - text: "02 - Bounds"
            href: part-04/tutorial-04-02-bounds.qmd
          - text: "03 - Constraints"
            href: part-04/tutorial-04-03-constraints.qmd
          - text: "04 - Advanced"
            href: part-04/tutorial-04-04-advanced.qmd
          - text: "05 - Transport"
            href: part-04/tutorial-04-05-transport.qmd
      - section: "05 Production Planning"
        contents:
          - text: "Lecture"
            href: part-05/lecture-production.qmd
          - text: "Tutorial"
            href: part-05/tutorial-production.qmd
      - section: "06 Warehouse"
        contents:
          - text: "Lecture"
            href: part-06/lecture-ordersplit.qmd
          - text: "Tutorial"
            href: part-06/tutorial-ordersplit.qmd
      - section: "07 Routing"
        contents:
          - text: "Lecture"
            href: part-07/lecture-routing.qmd
      - text: "***"
      - section: "Cheatsheets"
        contents:
          - text: "Julia"
            href: general/cheatsheet-julia.qmd
          - text: "JuMP"
            href: general/cheatsheet-jump.qmd
      - text: "FAQs"
        href: general/faq.qmd
      - text: "Literature"
        href: general/literature.qmd

  page-footer: 
    center: "Applied Optimization with Julia, Tobias Vlćek</br>CC BY-NC-SA 4.0" 
    right: 
      - icon: github
        href: https://github.com/beyondsimulations/Applied-Optimization
      - icon: linkedin
        href: https://linkedin.com/in/tobiasvlcek

format:
  html:
    theme: litera
    toc: true
    highlight-style: arrow
    linkcolor: "#a60000"
    code-copy: true
    code-link: true
    toc-location: right
    code-overflow: wrap
    code-block-bg: true
    code-block-border-left: "#AD1F00"

  pdf:
    documentclass: report
    geometry:
        - margin=1in
    fontfamily: roboto
    fontfamilyoptions: sfdefault
    colorlinks: true
    include-in-header: 
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
execute:
  freeze: auto


