project:
  type: website
  post-render:
    - helpers/convert_pypercent.py
    - helpers/convert_qmd_to_md.py
  render:
    - index.qmd
    - 404.qmd
    - general/*.qmd
    - lectures/*.qmd
    - tutorials/*.qmd
website:
  title: "Applied Optimization with Julia"
  repo-url: https://github.com/beyondsimulations/Applied-Optimization
  repo-actions: [edit, source, issue]
  site-url: https://beyondsimulations.github.io/Applied-Optimization
  bread-crumbs: true
  sidebar:
    style: floating
    logo: https://images.beyondsimulations.com/lectures/mj-romeo-juliet.png
    collapse-level: 1
    search: true
    contents:
      - text: "Welcome"
        href: index.qmd
      - text: "Syllabus"
        href: general/syllabus.qmd
      - text: "***"
      - text: "01 Introduction"
        href: lectures/lecture-01-introduction.qmd
      - section: "02 First Steps"
        contents:
          - text: "Lecture"
            href: lectures/lecture-02-firststeps.qmd
          - text: "01 - Variables"
            href: tutorials/tutorial-02-01-variables.qmd
          - text: "02 - Vectors"
            href: tutorials/tutorial-02-02-vectors.qmd
          - text: "03 - Comparisons"
            href: tutorials/tutorial-02-03-comparisons.qmd
          - text: "04 - Loops"
            href: tutorials/tutorial-02-04-loops.qmd
          - text: "05 - Dictionaries"
            href: tutorials/tutorial-02-05-dicts.qmd
      - section: "03 Data"
        contents:
          - text: "Lecture"
            href: lectures/lecture-03-packages.qmd
          - text: "01 - Functions"
            href: tutorials/tutorial-03-01-functions.qmd
          - text: "02 - Packages"
            href: tutorials/tutorial-03-02-handling.qmd
          - text: "03 - DataFrames"
            href: tutorials/tutorial-03-03-DataFrames.qmd
          - text: "04 - Input and Output"
            href: tutorials/tutorial-03-04-IO.qmd
          - text: "05 - Plotting"
            href: tutorials/tutorial-03-05-Plotting.qmd
      - section: "04 Optimization"
        contents:
          - text: "Lecture"
            href: lectures/lecture-04-jump.qmd
          - text: "01 - JuMP"
            href: tutorials/tutorial-04-01-jump.qmd
          - text: "02 - Bounds"
            href: tutorials/tutorial-04-02-bounds.qmd
          - text: "03 - Constraints"
            href: tutorials/tutorial-04-03-constraints.qmd
          - text: "04 - Advanced"
            href: tutorials/tutorial-04-04-advanced.qmd
          - text: "05 - Transport"
            href: tutorials/tutorial-04-05-transport.qmd
      - section: "05 Production"
        contents:
          - text: "Lecture"
            href: lectures/lecture-05-production.qmd
          - text: "Tutorial"
            href: tutorials/tutorial-05-production.qmd
      - section: "06 Warehouse"
        contents:
          - text: "Lecture"
            href: lectures/lecture-06-ordersplit.qmd
          - text: "Tutorial"
            href: tutorials/tutorial-06-ordersplit.qmd
      - section: "07 Routing"
        contents:
          - text: "Lecture"
            href: lectures/lecture-07-routing.qmd
          - text: "Tutorial"
            href: tutorials/tutorial-07-routing.qmd
      - section: "08 Districting"
        contents:
          - text: "Lecture"
            href: lectures/lecture-08-districting.qmd
          - text: "Tutorial"
            href: tutorials/tutorial-08-districting.qmd
      - section: "09 Safety"
        contents:
          - text: "Lecture"
            href: lectures/lecture-09-safety.qmd
          - text: "Tutorial"
            href: tutorials/tutorial-09-safety.qmd
      - section: "10 Intermission"
        contents:
          - text: "Lecture"
            href: lectures/lecture-10-intermission.qmd
          - text: "Tutorial"
            href: tutorials/tutorial-10-intermission.qmd
      - section: "11 Distancing"
        contents:
          - text: "Lecture"
            href: lectures/lecture-11-distancing.qmd
          - text: "Tutorial"
            href: tutorials/tutorial-11-distancing.qmd
      - section: "12 Metro"
        contents:
          - text: "Lecture"
            href: lectures/lecture-12-rail.qmd
          - text: "Tutorial"
            href: tutorials/tutorial-12-rail.qmd
      - section: "13 Recap"
        contents:
          - text: "Lecture"
            href: lectures/lecture-13-recap.qmd
          - text: "Tutorial"
            href: tutorials/tutorial-13-recap.qmd
      - text: "***"
      - section: "Cheatsheets"
        contents:
          - text: "Julia"
            href: general/cheatsheet-julia.qmd
          - text: "JuMP"
            href: general/cheatsheet-jump.qmd
      - text: "FAQs"
        href: general/faq.qmd
      - text: "Literature"
        href: general/literature.qmd

  page-footer:
    center: "Applied Optimization with Julia, Tobias Vlćek</br>CC BY-SA 4.0"
    right:
      - icon: github
        href: https://github.com/beyondsimulations/Applied-Optimization
      - icon: linkedin
        href: https://linkedin.com/in/tobiasvlcek
      - icon: envelope
        href: mailto:vlcek@beyondsimulations.com
      - icon: lock
        href: general/privacy.qmd

format:
  html:
    theme:
      - default
      - styles.scss
      - brand
    toc: true
    highlight-style: arrow
    code-copy: true
    code-link: true
    toc-location: right
    code-overflow: wrap
    html-math-method:
      method: mathjax
      url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    include-in-header:
      - general/header.html
    include-after-body:
      text: |
        <script src="https://cdn.jsdelivr.net/gh/beyondsimulations/web-embedded-chat@latest/floating-chat.js"></script>
        <script>
            new UniversalChatWidget({
                title: "Course Assistant",
                apiEndpoint: "https://model-proxy.vlcek-4b4.workers.dev/api",
                model: "applied-optimization",
                userMessageOpacity: 0.5,
                assistantMessageOpacity: 0.5,
                position: "bottom-right",
                windowHeight: 800
            });
        </script>

  hugo-md: default

  typst:
    papersize: a4

format-links:
  - html
  - format: typst
    text: PDF
    icon: file-pdf

bibliography: AppliedBib.bib

engine: julia

execute:
  freeze: auto

brand: _brand.yml
