---
title: "Frequently Asked Questions"
subtitle: "Answers to common questions"

html:
    highlight-style: arrow
---
## Unanswered Questions
If you have a question that is not answered here, please let me know by sending me an e-mail to [tobias.vlcek@uni-hamburg.de](mailto:tobias.vlcek@uni-hamburg.de?subject=Applied%20Optimization%3A%20%3CYour%20subject%3E) or by creating an issue on [GitHub](https://github.com/beyondsimulations/Applied-Optimization/issues).

## Contribution and Mistakes
If you have found a mistake in the course material or if you have any suggestion on how to improve the course, please let me know in the [following form](https://tally.so/r/3qWY8d) or by creating an issue on [GitHub](https://github.com/beyondsimulations/Applied-Optimization/issues).

---

## FAQs

### Is the course difficult?

In terms of difficulty, this is of course somehow complicated for me to assess. However, I have tried to make all the content as comprehensible as possible and really do ask you many questions in the lectures. If I have the impression that something has not been understood at all, then I take longer at that point. This semester is the first time I think the course is truly finished. I have adapted the slides based on feedback from the last two years and made all the examples as simple as possible.
**In a nutshell**: If you are interested in the subject and equations do not scare you, you will likely do great in the course.

---

### How can I download PDF slides from the lecture?

You have two options:

#### Option 1: Download from Github

- Follow this link to the [PDF slides on Github](https://github.com/beyondsimulations/Applied-Optimization/tree/main/pdf-slides).

#### Option 2: Generate yourself

1. First, open the lecture you want to download the slides from.
2. Then, click on the `RevealJS` button in the top right corner.
3. Now, click on the three stacked bars in the lower left corner.
4. Then, click on `Tools` in the upper left corner.
5. Now you can select `PDF Export Mode` and then save the slides as a PDF.

::: {.callout-note}
Unfortunately, this method does not work perfectly on all browsers. If you have a Chrome based browser, you should be fine.
:::

---

## How does the calculation of the bonus points work?

To reach the full 6 points, all exercises must be submitted. A maximum of 0.5 points can be earned per exercise. In the overview, '1' stands for successfully submitted, and '0.5' for submitted (but without attempting to solve everything). In the end, I calculate this as half or quarter points towards the total score.

---

## Can I take a sheet with me to the exam?

Yes, you can take a DIN A4 sheet with notes on both sides to the exam. Please note, that it should be **one** sheet of paper.
