---
title: "Tutorial II.I - Variables and Types"
subtitle: "Applied Optimization with Julia"

format:
    html:
        theme: litera
        highlight-style: arrow
        linkcolor: "#a60000"
        code-copy: true
        code-link: true
        toc: true
        toc-location: right
        code-overflow: wrap
    pdf: 
        documentclass: report
        geometry:
            - margin=1in
        fontfamily: roboto
        fontfamilyoptions: sfdefault
        colorlinks: true
    ipynb:
        code-copy: true
        code-overflow: wrap
---

# Introduction to Variables and Types in Julia

Welcome to this interactive Julia tutorial which introduces the basics of variables and types. Understanding variables and their types is crucial as they are the building blocks of any program. They determine how data is stored, manipulated, and how efficiently your code runs.

This script is designed to be interactive. Follow the instructions, write your code in the designated code blocks, and then execute the corresponding code. Each exercise is followed by an @assert statement that checks your solution.

The easiest way to run the code is by using IJulia. Start Julia, and type `using IJulia; notebook()` in the Julia prompt. This will open a new browser window where you can run the code. If you have not installed IJulia yet, you can do so by typing `]` in the Julia prompt to open the package manager, and then installing IJulia by typing `add IJulia`.

:::{.callout-note}
Always replace 'YOUR CODE BELOW' with your actual code.
:::

# Section 1: Variables

Introduction to Variables: A variable in Julia can be used to store data like numbers, text, or more complex types. To declare a variable in Julia, simply assign a value to a name: `variable_name = value`.

## Exercise 1.1

Declare a variable named 'x' and assign it the value 1.

```{julia}
#| eval: false
# Declare a variable named 'x' and assign it the value 1
# YOUR CODE BELOW

# Test your answer
@assert x == 1 "Check again, the value of x should be 1. Remember to assign the value directly to x."
println("Great, you have correctly assigned the value $x to the variable 'x'.")
```

## Exercise 1.2

Declare a variable named 'hi' and assign it the string  "Hello, Optimization!".

```{julia}
#| eval: false
# Declare a variable named 'hi' and assign it the string  "Hello, Optimization!"
# YOUR CODE BELOW

# Test your answer
@assert hi == "Hello, Optimization!" "Make sure the variable 'hi' contains the exact string \"Hello, Optimization\"!"
println("Good, the variable 'hi' now states \"$hi\".")
```

# Section 2: Basic Types

Julia is a dynamically typed language, yet it allows you to indicate types explicitly. Understanding types is crucial for writing efficient Julia code. Common basic types include Integers, Floats, Booleans, and Strings. To check the type of a variable, use the `typeof()` function.

## Exercise 2.1

Create an Integer variable 'answerUniverse' and set it to 42.

```{julia}
#| eval: false
# Create an Integer variable 'answerUniverse' and set it to 42
# YOUR CODE BELOW

# Test your answer
@assert answerUniverse == 42 "The variable 'answerUniverse' should hold 42."
println("Great, the answer to all questions on the universe is $answerUniverse now.")
```

## Exercise 2.2

Create a Float variable 'money' and set it to 1.35.

```{julia}
#| eval: false
# Create a Float variable 'money' and set it to 1.35
# YOUR CODE BELOW

# Test your answer
@assert money == 1.35 "The variable 'money' should hold the Float64 1.35."
println("Perfect, the you have stored $money in the variable 'money'.")
```

## Exercise 2.3

Create a Boolean variable 'isStudent' and set it to true.

```{julia}
#| eval: false
# Create a Boolean variable 'isStudent' and set it to true
# YOUR CODE BELOW

# Test your answer
@assert isStudent == true "The variable 'isStudent' should be set to true."
println("Correct, you are a student now.")
```

## Conclusion

Congratulations! You have completed the first tutorial on Variables and Types. You've learned about the basics of variables, integers, floats, booleans, and strings. Continue to the next file to learn more.

{{< include ../include/tutorial_end.qmd >}}