---
title: "Tutorial XIII - Recap and Discussion"
subtitle: "Applied Optimization with Julia"

format:
    html:
        theme: [litera, ../styles.scss]
        highlight-style: arrow
        linkcolor: "#a60000"
        code-copy: true
        code-link: true
        toc: true
        toc-location: right
        code-overflow: wrap
    ipynb:
        code-copy: true
        code-overflow: wrap

---

# Introduction

{{< include ../include/tutorial_end.qmd >}}

This will (hopefully) be the easiest tutorial of the entire course. Essentially, we will just use today's tutorial as a last chance for you to ask questions and discuss the content of the course. 

# Feedback on the lecture series

To receive half a bonus point, you will just need to complete a short feedback form on the lecture series before the exam. It is not from the university, but from me, and I would be truly grateful for your honest opinion and feedback. Your feedback is important to me and has absolutely no influence on your grade!

# Questions

You can answer the questions directly online, but I'll give you a heads up with the list of questions before. In total I think it will take you about 15 - 20 minutes to complete the form - that's not too bad given that you will receive half a bonus point for it, right?

In all honesty, I know this is much to ask of you - especially given that you will only receive half a bonus point for it and the exams are coming up. However, I think it is very important for me to get your honest opinion and feedback. I will use it to improve the course for future students, as well as for my future teaching.

## Julia Programming Experience

As this course introduced many of you to Julia programming, I'm particularly interested in your experience learning and working with this language. Your feedback will help determine if Julia remains the right choice for future iterations of this course and what additional programming support might be needed.

- How did you find the learning experience of Julia in this course?
- What were the greatest challenges you faced while learning Julia?
- Should I have used a different programming language for this course?
- Should we have covered programming with AI in this course?

## Course Content and Structure

The course covered a wide range of optimization topics, from basic concepts to advanced applications. I'd like to understand which parts resonated with you and which areas might need adjustment in terms of depth and clarity.

- Which topics would you have preferred to explore in more depth?
- Was there any topic you felt was covered too much?
- Which of the topics would you recommend removing in exchange for a new topic in the future?
- How could the tutorial instructions be improved for clarity?

## Learning Experience

The course utilized a web-based format with interactive elements and a bonus point system. Your feedback on these teaching methods and course mechanics will be valuable for improving the learning experience.

- How did you find the website format for learning the material?
- What additional elements would enhance your learning?
- How could the teaching of the course be improved?
- How could the bonus point system be improved?

## Future Improvements

Looking ahead, I want to ensure this course continues to evolve and meet students' needs. Your suggestions for future developments and overall reflections will help shape the course's direction.

- What type of exam would best demonstrate your understanding?
- Please summarize your overall experience with the course?
- Is there any course at the university you would like to see in the future?
- Have I missed anything important? Here is your chance!

# Feedback Form

<iframe data-tally-src="https://tally.so/embed/w58Z5E?alignLeft=1&hideTitle=1&transparentBackground=1&dynamicHeight=1" loading="lazy" width="100%" height="181" frameborder="0" marginheight="0" marginwidth="0" title="Feedback: Applied Optimization"></iframe>
<script>var d=document,w="https://tally.so/widgets/embed.js",v=function(){"undefined"!=typeof Tally?Tally.loadEmbeds():d.querySelectorAll("iframe[data-tally-src]:not([src])").forEach((function(e){e.src=e.dataset.tallySrc}))};if("undefined"!=typeof Tally)v();else if(d.querySelector('script[src="'+w+'"]')==null){var s=d.createElement("script");s.src=w,s.onload=v,s.onerror=v,d.body.appendChild(s);}</script>

# Wrap-up

Thank's for your participation! I wish you all the best for your exam and I hope you enjoyed the course! If you have any questions, please feel free to ask me or send me an email. We offer seminars each summer semester where you can explore different topics in more depth. In case you are interested in writing your thesis with me, please let me know and we can discuss potential topics.

